### ISSUE TITLE
having a flashlight in your action bar will duplicate and swap itself with the PDA action when you grab your PDA

### ISSUE THREAD

**Issue by JoeHammad1844** [Goob-Station/Goob-Station#1078]
## Description

title
**Reproduction**

have PDA light action
pick up a flashlight
now put your PDA in your hand
you will now have two flashlight actions and your PDA will be at the front of your action bar

**Comment by Aviu00** [comment]
Fixed by #1070

**Comment by JoeHammad1844** [comment]
Move still a problem 16 hours after it's fixed :finnadie:

**Comment by Aviu00** [comment]
> Mfw still a problem 16 hours after it's fixed :finnadie:

Maybe the server has not updated yet.
