### ISSUE TITLE
You can pick up a Ripley while in a Ripley

### ISSUE THREAD

**Issue by Yushe** [Goob-Station/Goob-Station#1103]
## Description
While piloting a Ripley APLU that has a hydraulic clamp attached you can pick up another Ripley APLU.

**Reproduction**
Click on another Ripley APLU to pick it up.

**Screenshots**
![Screenshot 2024-12-08 140303](https://github.com/user-attachments/assets/1a581639-27e4-4cb2-8088-e25cb646757f)

**Comment by Piras314** [comment]
feature
