### ISSUE TITLE
Make ore bags printable on autolathe

### ISSUE THREAD

**Issue by 7-62x54r** [Goob-Station/Goob-Station#1136]
Why it's not a feature by now, it's just a bag with funny magnet cmon. Greytide magnet asteroid mining is ass without asking cargo for one and salvs just steal theirs onto reclaimers.
Make it require cloth and steel (due to magnet part) idfk.

**Comment by BombasterDS2** [comment]
https://github.com/Goob-Station/Goob-Station/pull/1255
