### ISSUE TITLE
Enable Cryosleep Rejoining

### ISSUE THREAD

**Issue by Beridot** [Goob-Station/Goob-Station#1140]
Enable  game.cryo_sleep_rejoining.

### Why? 

Cause why NOT, why is this not enabled?? It would enable people to leave whenever they want and come back whenever they want.

**Comment by JustSome1Nearby** [comment]
Do you remember, that when Joining the round via cryo, you get an antag-roll chance. NOW, if you didnt get antag, you go into cryo... and back out! Gambling!

**Comment by Aineias1** [comment]
Bad idea, there's a good reason that we can't get out of cryo rn

**Comment by Beridot** [comment]
and yet no one told me about these problem, untill now. mfw

**Comment by Piras314** [comment]
people will metagame it so badly, just play on another server
