### ISSUE TITLE
INVISIBLE SKINWALKERS QUESTION MARK EXCLAMATION POINT

### ISSUE THREAD

**Issue by BeeRobynn** [Goob-Station/Goob-Station#121]
## Description
Basically through some mischief that has something to do with infection or darkness anomalies, skinwalkers can become completely invisible from people and are untargetable by ai mobs

**Reproduction**
Hyoid became infected as a skinwalker, and upon dying and walking out of a darkness anomaly, became invisible to the entire to the entire crew and becomes unable to be seen by any ai mob

**Screenshots**
[https://youtu.be/SnvcyE7RzHM](url)

this should be uploaded by the time someone sees

**Additional context**
darius is smelly not me >:(((

**Comment by Verbalase** [comment]
Skinwalkers were removed, but if they happen to come back, you can reopen this..

Or make a new issue, not sure.

**Comment by CatMagic1** [comment]
they ARE coming back reopen this shit it isn't fixed

**Comment by Verbalase** [comment]
> they ARE coming back reopen this shit it isn't fixed

Kay.

**Comment by Aidenkrz** [comment]
Will be fixed when skinwalkers are reworked. closing issue for now
