### ISSUE TITLE
Unable to butcher monkeys and kobalds

### ISSUE THREAD

**Issue by Yushe** [Goob-Station/Goob-Station#1284]
## Description
Because of the surgery update chefs are unable to butcher monkeys and kobolds through the drop down menu.
If chefs don't have meat spikes they can't get sources of meat from monkeys and kobolds.

**Screenshots**
![Screenshot 2024-12-28 092451](https://github.com/user-attachments/assets/fd323ed2-76ef-4c0e-929f-ad8bee3de4b9)

**Comment by Aviu00** [comment]
I think you aren't supposed to butcher them without meat spike. Also meat spike can be constructed for 15 steel.

**Comment by deltanedas** [comment]
youve always had to meatspike

**Comment by BombasterDS2** [comment]
Monkeys are not butcherable like all humanoids species

**Comment by Yushe** [comment]
I'm pretty sure they were butcherable in the offical codebase when I last played on wizard's den.
