### ISSUE TITLE
Chamleon Projection Bug

### ISSUE THREAD

**Issue by Verbalase** [Goob-Station/Goob-Station#189]
## Description
The Chamleon projection item makes players invisible if they disguise into something worn.

**Reproduction**
I guess disguise into something that can be worn on your character. (Jumpsuits, Ears, etc)

**Screenshots**
Can't exactly screenshot it, but you can attempt it yourself.

**Additional context**
Dunno.

**Comment by CatMagic1** [comment]
Already reported on upstream

**Comment by Verbalase** [comment]
Closed then.
