### ISSUE TITLE
Notice of license violation

### ISSUE THREAD

**Issue by NullWanderer** [Goob-Station/Goob-Station#223]
[Goob-Station/Goob-Station](https://github.com/Goob-Station/Goob-Station) is currently in violation of Delta-V's AGPL license by taking some of it's code while under the MIT license. This isn't allowed under the conditions of this license, and we will submit a DMCA takedown notice if these issues aren't fixed within 24 hours of this issue being made.

List of offending content:
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/VoiceMask/SyrinxVoiceMaskComponent.cs#L13-L18
Taken from [this](https://github.com/DeltaV-Station/Delta-v/commit/31dfe787a08a574c1b3f1e96bd127bbc6ae117fe) commit.
-------------

https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/Implants/SubdermalBionicSyrinxImplantSystem.cs#L29-L31
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/Implants/SubdermalBionicSyrinxImplantSystem.cs#L36
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/Implants/SubdermalBionicSyrinxImplantSystem.cs#L46
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/Implants/SubdermalBionicSyrinxImplantSystem.cs#L52-L65
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/Implants/SubdermalBionicSyrinxImplantSystem.cs#L143-L149
Taken from [this](https://github.com/DeltaV-Station/Delta-v/commit/31dfe787a08a574c1b3f1e96bd127bbc6ae117fe) commit 
-------------
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/Implants/SubdermalBionicSyrinxImplantSystem.cs#L93
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/Implants/SubdermalBionicSyrinxImplantSystem.cs#L103
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/Implants/SubdermalBionicSyrinxImplantSystem.cs#L60
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Server/DeltaV/Implants/SubdermalBionicSyrinxImplantSystem.cs#L130-L131
Taken from [this](https://github.com/DeltaV-Station/Delta-v/commit/8a4cfda6d77270618f1c36564ef10cb837b4d5ac) commit
-------------
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Shared/DeltaV/Abilities/CCVars/DCCVars.cs
Taken from [this](https://github.com/DeltaV-Station/Delta-v/commit/b32a3446ff01bdc1eb6c8aeae32125e2a2bcdee7) commit
-------------
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Shared/DeltaV/StepTrigger/Component/NoShoesSilentFootstepsComponent.cs
Taken from [this ](https://github.com/DeltaV-Station/Delta-v/commit/49d3c45d0d7c499853cc3a1559cb2d9bd1e91e0a)commit
------------
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Client/Nyanotrasen/Overlays/DogVisionSystem.cs#L26
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Client/Nyanotrasen/Overlays/DogVisionSystem.cs#L45
https://github.com/Goob-Station/Goob-Station/blob/9ec2113c7b9e68cf2d277762f6e82973c677f617/Content.Client/Nyanotrasen/Overlays/DogVisionSystem.cs#L54-L60
Taken from [this](https://github.com/DeltaV-Station/Delta-v/commit/b32a3446ff01bdc1eb6c8aeae32125e2a2bcdee7) commit

Splitting this up due to it getting very large. Prototype violations will be in a comment under this issue. The above are all the code violations I found. There may be more, I advise you to cross reference everything yourself against out commit history.

If these instances are not removed from this repository within 24 hours, we will submit a DMCA takedown notice.

**Comment by Verbalase** [comment]
> I'm actually too lazy to go over all of the yaml changes. At a really quick glance, I found some minor violations, and several things belonging to [Einstein Engines](https://github.com/Simple-Station/Einstein-Engines), which we aren't going to claim.
> 
> I advice you to go over everything yourself and ensure all license violations are removed, or relicensing to AGPLv3 to keep using this content.

real

**Comment by Aidenkrz** [comment]
License has been updated to APGL V3

**Comment by Aidenkrz** [comment]
> You still have to make the relicense clear in the readme.

It's been updated.
