### ISSUE TITLE
Harpy characters cannot equip the jumpsuit they spawn with.

### ISSUE THREAD

**Issue by GreyMario** [Goob-Station/Goob-Station#252]
## Description
Harpies cannot equip jumpsuits. They spawn with jumpsuits. If they take off their jumpsuit, they can't put it back on.

Bird up.

**Reproduction**
1. Be a Harpy.
2. Get nekkid.
3. Realize that's a bad idea.
4. Realize your jumpsuit no longer fits. ("This doesn't fit!")

**Comment by Bloomyex** [comment]
It's *ALL* of the clothes that go in that slot that won't fit. Even worse!!!

**Comment by GreyMario** [comment]
It looks like the code is intended to be a Skirt tag whitelist, but yeah I just tested with a passenger jumpskirt and it is indeed Shitting Itself.

Also--salvage jumpskirts don't exist, So There's That Problem?

**Comment by Aidenkrz** [comment]
Ah I forgot to add a piece of code, it'll be fixed soon.

**Comment by Bloomyex** [comment]
Good to know!
