### ISSUE TITLE
Website link

### ISSUE THREAD

**Issue by Piras314** [Goob-Station/Goob-Station#263]
## Description

The website link is still set to spacestation14.io, but we have goobstation.com now and it should be changed to that.

**Reproduction**

n/a
**Screenshots**

n/a
**Additional context**

n/a

**Comment by Piras314** [comment]
The link I'm referring to is on the sidebar of Github, next to the description "Wizden, but more random"

**Comment by Aidenkrz** [comment]
@Verbalase problem, i can't edit the repo.

**Comment by Verbalase** [comment]
Fixed.
