### ISSUE TITLE
Chrono Legionnaire

### ISSUE THREAD

**Issue by Aidenkrz** [Goob-Station/Goob-Station#294]
Port [chrono legionnaire from TG](https://tgstation13.org/wiki/Chrono_Legionnaire)
Take the modsuit and TEM from this, and put it over a RCD that can deconstruct players.

This is mostly for admemes and removing players with bad IC names, similar to the terminator ghost role.

**Comment by BombasterDS** [comment]
I made chronolegioneer for another server, but they conceptually different from TG version (because i didn't found any video with them :|). 

It was made for admemes, but need some rework and code cleanup - https://github.com/MetalSage/space-stories-archive/pull/108
