### ISSUE TITLE
Re-add atmos remote

### ISSUE THREAD

**Issue by Piras314** [Goob-Station/Goob-Station#299]
Re-add the atmos bolting remote

**Comment by a-person5660** [comment]
i'm on this o7

**Comment by Aidenkrz** [comment]
> remove some stupid thief objs in the same PR too. 

Make this a separate issue, this is out of scope for this issue

**Comment by Aidenkrz** [comment]
Fixed in https://github.com/Goob-Station/Goob-Station/pull/309.
