### ISSUE TITLE
Cargo order timeouts

### ISSUE THREAD

**Issue by Piras314** [Goob-Station/Goob-Station#306]
This would allow cargo items to have a timeout on how often you can order them. It would be similar to the uplink timeout, but it would be based on the last time it was ordered instead of general station time.

This should be applied to the cargo lottery crate at first, and possibly other things later.

It would grey things out in the main selection menu and disallow you from adding them to the ordering list to be approved, and would disallow you from approving already existing orders if the timeout is still on hold.

**Comment by a-person5660** [comment]
imo QM should be able to overide it unless theres a good reason not to (armoury crates?)

**Comment by a-person5660** [comment]
(i want to waste all of the money on grand lotteries)

**Comment by Piras314** [comment]
grand lottery only being allowed to be ordered once every say, 10 minutes is the whole point of this, no override, nothing, so that cargo actually invests in the station and not in 1tc guns and cheap thrills

**Comment by jellygato** [comment]
I'm comfortable with QM being allowed to override this on some things. If we wanna get crazy with it, we might be interested in having the other cargo crew be able to democratically override the QM on this, just in case we get a power-hungry QM or something. (After writing it, I'm no longer thinking it'd be worth the effort to put in a system to override a QM vote but I'm still gonna write it here anyway.)

**Comment by Piras314** [comment]
We can have an override if this gets added for armory crates, but for grand lotteries (the current scope) there shouldn't be an override.

**Comment by Teapug** [comment]
Would simply adding a restockTime suffice?
even if it has a cooldown, people could just order multiple at once.
im not sure how to limit the amount of items that can be purchased in a single order

**Comment by Piras314** [comment]
we would have to make it so that you can't order multiple at once
