### ISSUE TITLE
Cool Shit I thought of before

### ISSUE THREAD

**Issue by CatMagic1** [Goob-Station/Goob-Station#351]
- Energy guns, there's already a closed pr for this with sprites but I dunno how usable the code is
- "Mindslave" implants, from the uplink and they let you turn someone into a syndie who can help you. Can't be used on people with mindshield implants until you remove the mindshield implant (also let people remove mindshields since that's cool and it'd lower murderboning during revs).
- Clown syndie item that converts all your organs into hostile clown entities, need I explain more? Might be janked by newmed, can be pretty easily coded by just making a polymorph entity with the organs.
- The mime books, they're really cool and seriously can't be that hard to re-add, fuck you durk.
- Pressure sealed jumpsuits and gas masks, like a t2 civilian tech. They're really useful since they don't slow you down and you could wear armor over them.
- Also re-add craftable nuke and make the normal version have the current syndie version's blast and make the syndie version have a larger blast and also make them cheaper because fuck you durk.
- Also re-add clown cuffs someway somehow
- Oh also a Shade antag that is attached to a player similar to holos and only the player can see them, maybe make it tell them to kill people or some shit or maybe make it take control of the player randomly or when they get knocked unconscious. 

yeah fuck you durk

**Comment by CatMagic1** [comment]
fuck you durk

**Comment by Piras314** [comment]
can't be too hard to port this over yourself you just have to move it into goobstation folders

**Comment by CatMagic1** [comment]
> can't be too hard to port this over yourself you just have to move it into goobstation folders

I deleted my repo and all my git shit

**Comment by CatMagic1** [comment]
piss you
