### ISSUE TITLE
terrible revs feedback/design flaws

### ISSUE THREAD

**Issue by JoeHammad1844** [Goob-Station/Goob-Station#372]
## Description

when all heads are killed, a 5 minute shuttle is called, why the fuck would revs LEAVE the station they just took over, the entire point is to kill the heads and rule over the station a different way, not to leave

there is also no announcement or shuttle call when all the headrevs die

also, evac arriving is an issue. in ss13 it can be called (as not to metagame) but cannot arrive, this prevents command from pussying out early or just waiting it out in maints, no shuttle forces conflict which is more engaging and fun. it also doesnt make sense logic wise because the point of the revolution is to overthrow the heads and run the station in a different way

revs should just end instantly when all the heads/headrevs are dead (this was merged but shadow reverted )

**Comment by JoeHammad1844** [comment]
outdated but related issue

https://github.com/space-wizards/space-station-14/issues/20858

**Comment by JoeHammad1844** [comment]
^ point 5 in that is for midround revs by the way

**Comment by FoxxoTrystan** [comment]
> ## Description
> when all heads are killed, a 5 minute shuttle is called but the announcement doesnt mention revs won, just that the shuttle was called additionally, why the fuck would revs LEAVE the station they just took over, the entire point is to kill the heads and rule over the station a different way, not to leave
> 
> there is also no announcement or shuttle call when all the headrevs die
> 
> also, evac arriving is an issue. in ss13 it can be called (as not to metagame) but cannot arrive, this prevents command from pussying out early or just waiting it out in maints, no shuttle forces conflict which is more engaging and fun. it also doesnt make sense logic wise because the point of the revolution is to overthrow the heads and run the station in a different way
> 
> revs should just end instantly when all the heads/headrevs are dead

If i remember how i seen Revs being played, when all Head are Killed/Exiled normally the Revs wins and the game ends, no shuttles.

I Supose making the system end the round directly instead of the shuttle is extremly easy to do.

**Comment by JoeHammad1844** [comment]
> If i remember how i seen Revs being played, when all Head are Killed/Exiled normally the Revs wins and the game ends, no shuttles.

yeah thats what im asking for

**Comment by misandrie** [comment]
> why the fuck would revs LEAVE the station they just took over

If a rev wincond wasnt achieved in 5 minutes with surgically murdering and gibbing all command staff you are look at 20 (optimistic estimate) people removed off the round entirely. Additionally I've not seen any revs assuming staff positions after the wincond has been triggered, as its treated as a team deathmatch round more than anything.

**Comment by Piras314** [comment]
@Aidenkrz

**Comment by JoeHammad1844** [comment]
gaming rework fixed every issue i had basically
