### ISSUE TITLE
default supermatter setups are bad/broken

### ISSUE THREAD

**Issue by a-person5660** [Goob-Station/Goob-Station#380]
multiple stations supermatter setups are broken/dangerous to use at round start due to their layout and require massive revamping to make usable.  some arent even connected properly to the power grid.

**Comment by whateverusername0** [comment]
IC issue :trollface:

**Comment by terezi-station** [comment]
someone teach me what SM even needs and ill map em

**Comment by a-person5660** [comment]
This has been mostly fixed, i would like to see more stations get SM engines though.
