### ISSUE TITLE
Borgs missing flashlight after a recent update

### ISSUE THREAD

**Issue by SkippyMcSkips** [Goob-Station/Goob-Station#388]
## Description
It seems after a recent update that Borgs don't spawn with flashlights anymore. 

**Reproduction**
Spawn as a Cyborg
Notice that you have no flashlight
Cry

**Screenshots**
![image](https://github.com/Goob-Station/Goob-Station/assets/107330854/99747bb1-245d-4b3b-85e5-77c95c72ce09)

**Comment by Piras314** [comment]
Seems like an issue with upstream I'm afraid.

**Comment by SkippyMcSkips** [comment]
I'd check on the Wizden servers but I don't have enough playtime to spawn as a Borg. 

Not sure where the issue lies, just wanted to report it since I noticed it within the last few days.

**Comment by SkippyMcSkips** [comment]
I've raised this issue upstream: https://github.com/space-wizards/space-station-14/issues/29916

Can probably close this one out.
