### ISSUE TITLE
Syndicate objectives and their balance/state needs discussion and possibly changes.

### ISSUE THREAD

**Issue by TooSillyFennec** [Goob-Station/Goob-Station#401]
Pretty much what it says. Since den by really, accident changed objective balance recently, and the old state is debatably still bad objectives probably need actual changes to balance. maybe even allowing players more freedom with how their objectives spawn- like how much or what either TG does with allowing custom set objs or VG's basically do whatever objective choice in character creation. originally from an attempt to revert the effect but not the bug fix that den added in this PR: #394 

Also, here's an image of the current generation of synd objs for reference. 
![objs](https://github.com/user-attachments/assets/2dc28f8c-7629-405a-95f1-212fe171b2f2)

**Comment by Piras314** [comment]
would be cool to have a progression where you can take an objective out of the options given to you, and depending on the objective it will give you different amounts of tc and then rinse and repeat

**Comment by TooSillyFennec** [comment]
> would be cool to have a progression where you can take an objective out of the options given to you, and depending on the objective it will give you different amounts of tc and then rinse and repeat

Similar to TG's progtot, or something else? TG Progtot has some problems personally, and I've seen it been disliked a decent bit.

Also, that did remind me: Contractor kits are a thing paradise still has and TG used to. I actually have a contractor baton in one of my branches, but the textures were a little fucked and never well... worked. When they are cleaned up I'll probably PR the baton.

However, yeah, progression's very interesting as a mechanic so long as it's not TG progtot level half assed. Might be better as a like, select if you want the progression or the normal 100 TC.

**Comment by Piras314** [comment]
closing this because it's too vague, if anyone's interested I plan on setting our docs up better and this is the kind of thing that probably should have a design doc, but at least should be an issue with a proposal
