### ISSUE TITLE
Balance proposition: syndicate rocket launcher

### ISSUE THREAD

**Issue by JoeHammad1844** [Goob-Station/Goob-Station#404]
i couldnt find an ideaguys channel so im putting this here lololololol

## Description

On the nukie planet, nukies will get a free rocket launcher with one spare rocket and no way to obtain more, intended to be used as an entry device to instantly destroy reinforced windows or regular walls. 
(from memory it doesn't even completely destroy regular walls, just turns them into girders)
It could also be used in combat but you only get two total shots and its hard to store

Also, it would be really funny for them to slip and have the clown shoot them with it

**Comment by Verbalase** [comment]
React to the Dev Channel role in #welcome and the ideaguys forum will appear for you.

**Comment by Piras314** [comment]
I like this idea

**Comment by JoeHammad1844** [comment]
> React to the Dev Channel role in #welcome and the ideaguys forum will appear for you.

thanks

**Comment by CatMagic1** [comment]
This got you banned from the wizden repo didn't it?

**Comment by JoeHammad1844** [comment]
> This got you banned from the wizden repo didn't it?

no, that would be the syndicate RCD textures

**Comment by Teapug** [comment]
What about a single use rocket launcher that cannot be reloaded and can be purchased by nukies for 150 TC?
