### ISSUE TITLE
Changeling can be gibbed by crew by using a meat spike

### ISSUE THREAD

**Issue by Nousagi37** [Goob-Station/Goob-Station#445]
## Description
The Changeling can be gibbed with a meat spike, and can not be resurrected

**Reproduction**
Kill the Ling, and drag the un-resurrected Ling onto a meat spike, and wait till the action is completed and the changeling is now gibbed and permanently dead

**Comment by a-person5660** [comment]
might have been fixed in the most recent ling fix, idr :trollface:

**Comment by Aidenkrz** [comment]
why is this an issue?

**Comment by a-person5660** [comment]
idk but last i heard from john he wanted it so they could only die from starving.

**Comment by Piras314** [comment]
i think this is an unintended feature tbh

**Comment by Verbalase** [comment]
Unintended feature from what I think. If not, feel free to make a new issue. (or reopen...?)
