### ISSUE TITLE
chrono legionnaire's small issues

### ISSUE THREAD

**Issue by GitHubUser53123** [Goob-Station/Goob-Station#451]
1. most descriptions need a period in the end.
![image](https://github.com/user-attachments/assets/0e1d5558-752f-4549-958b-704c3ff72765)
![image](https://github.com/user-attachments/assets/25a91368-8dd8-49f2-bd16-4a51d5a79a90)
![image](https://github.com/user-attachments/assets/1dbf62fc-5b48-40d1-87d9-2cbed4753b11)
![image](https://github.com/user-attachments/assets/ecce8f3c-15f5-4f12-9fd9-ccda3e067fc9)
2. the sonic screwdriver is annoying, maybe change its sound

https://github.com/user-attachments/assets/000bda4f-5eed-42a6-98a4-eda76a46d5d4

**Comment by Aidenkrz** [comment]
It's an admin only loadout that should only be used sparingly.

**Comment by GitHubUser53123** [comment]
still why not fix it??

**Comment by Verbalase** [comment]
> still why not fix it??

You can PR the punctuations for the text if you’d like. The screwdriver sound I can only assume is annoying to YOU, so just leave it alone.

Unless you’re for some reason going to spam it, I don’t know.
