### ISSUE TITLE
Ghostbar bug: Zombies gamemode counts ghost bar visitors as nonconverted players

### ISSUE THREAD

**Issue by BombasterDS** [Goob-Station/Goob-Station#460]
## Description
Ghostbar visitors count as suvivors in zombie gamerule (non affect playing experience, but not cool see 68% zombie effect when only 2 players survived)

**Reproduction**
1. Zombie gamerule
2. Go ghostbar after death
3. You now count as survivor

**Comment by VMSolidus** [comment]
https://github.com/Simple-Station/Einstein-Engines/pull/652
Actually a pretty easy fix.

**Comment by Aidenkrz** [comment]
> ## Description
> Ghostbar visitors count as suvivors in zombie gamerule (non affect playing experience, but not cool see 68% zombie effect when only 2 players survived)
> 
> **Reproduction**
> 
> 1. Zombie gamerule
> 2. Go ghostbar after death
> 3. You now count as survivor

For some reason in the end screen the percentage is set to include off-station players, but in the actual calculation to end the round it isn't. Literally just have to set a boolean from true to false, it'll be included in the next ghost bar update.
