### ISSUE TITLE
Gondola is not Finnish enough

### ISSUE THREAD

**Issue by BasedUser** [Goob-Station/Goob-Station#501]
## Description
pls help, i have problem :DDDDD
i are become gondola to bartiotism (🇫🇮🇫🇮) bud id is silenced

dis issue is for tracking burboses and needs no ebin gamer attention :DDDDDDD

**Reproduction**
1. speak

**Screenshots**
N/A

**Additional context**
Fixable by adding an intermediate gondola accent for when you eat any gondola meat (to mimic SS13 behavior, but with some spice). The mechanic doesn't yet exist but it's part of the issue anyway.  

&nbsp;

&nbsp;

&nbsp;

<details><summary></summary>:DDDDDDDDDDDDDDDDD</details>

**Comment by Verbalase** [comment]
what
