### ISSUE TITLE
Putting a bagged felinid onto a burger despawns them

### ISSUE THREAD

**Issue by Scruq445** [Goob-Station/Goob-Station#518]
## Description
Putting a felinid in a bag, and then putting that bag onto a burger bun, despawns (round removes) them from the game

**Reproduction**
grab duffel bag, or bag big enough for a felinid
get a knife and a burger bun and cut the bun in half
put said bag onto bun
round removed

**Screenshots**

[](https://github.com/user-attachments/assets/d406d586-6d95-4d15-92c6-aee69c3b9c73)

**Comment by RealFakeSoof** [comment]
Ooooooooh this is a beeg one

**Comment by yglop** [comment]
also works with pet carriers 

https://github.com/user-attachments/assets/147cd3f1-43d6-40b9-9093-8c32df61af45

**Comment by Aidenkrz** [comment]
Who woulda thought that putting someone in a burger kills them 🙀

**Comment by Aidenkrz** [comment]
This isn't an issue, this is it working as intended. If you do it you just get banned for self antag.

**Comment by a-person5660** [comment]
It should probably do something other than delete them tho, I imagine this may cause issues with objectives and unique items.

**Comment by Scruq445** [comment]
> This isn't an issue, this is it working as intended. If you do it you just get banned for self antag.

what's so intentional of making a bun delete them from reality

**Comment by Scruq445** [comment]
and getting banned for self-antagging by doing it seems like a bandaid way to fix it

**Comment by Scruq445** [comment]
> Who woulda thought that putting someone in a burger kills them 🙀

also how the fuck does that even make sense

**Comment by Piras314** [comment]
putting someone on a burger bun shouldn't despawn them, this is a bug.

however it should probably be solved upstream as seemingly from @yglop 's video it happens with any species using a pet carrier
