### ISSUE TITLE
Switching inventories doesn't work properly

### ISSUE THREAD

**Issue by SkippyMcSkips** [Goob-Station/Goob-Station#553]
## Description
When swapping between inventories, the second inventory you try to open doesn't display.

**Reproduction**
Switch between any two inventories (ie, a toolbelt and a backpack). You will notice the first inventory you opened close normally, but the second one will briefly flash on-screen for a split second before disappearing. The second inventory is actually still open, but is invisible.

**Screenshots**
First inventory opened:
![image](https://github.com/user-attachments/assets/d2a82686-108e-446b-b362-4df4ee02e33d)

Second inventory opened:
![image](https://github.com/user-attachments/assets/f03b9753-8335-49f5-a9bf-4903cac4382e)

A split second later, the second inventory is now invisible (no buttons pressed):
![image](https://github.com/user-attachments/assets/362817aa-e78e-406c-a4c4-cb5df73d2692)

If you right-click the second inventory, you can see it shows "Close Inventory", meaning it's still open but just not visible:
![image](https://github.com/user-attachments/assets/90a24084-d0f2-431c-92d0-8fa8cdf2323d)

**Additional context**
This is a fairly recent bug, so may have been introduced by one of the last couple updates.

**Comment by Piras314** [comment]
I think this bug was in when newstorage was added, I dunno if it was fixed for a time between then but yeah.

**Comment by Piras314** [comment]
https://github.com/space-wizards/space-station-14/issues/31466

**Comment by Piras314** [comment]
resolved by https://github.com/space-wizards/space-station-14/pull/31616

will mark this as fixed when I merge upstream

**Comment by Piras314** [comment]
resolved by #555
