### ISSUE TITLE
Sec hardsuit buffs

### ISSUE THREAD

**Issue by Piras314** [Goob-Station/Goob-Station#634]
Security hardsuits are way too sluggish and weak.

There should also be a secondary security hardsuit with very little speed penalty and very little armour, especially for #633 missions that aren't against known armed and dangerous people.

**Comment by JoeHammad1844** [comment]
I think this would be a good way to introduce voidsuits as an armor class I general

I'm taking this from baystation12, where voidsuits act like hardsuits do currently and hardsuits act like MODsuits on other servers

For this specific example i'm thinking of a security voidsuit with 10% slowdown, 25% resistances to blunt, slash and explosive damage, 30% for pierce and 20% for heat.

**Comment by JoeHammad1844** [comment]
Forgot to clarify, I mean for voidsuits to have less slowdown but also less damage resistances in general
