### ISSUE TITLE
Reinforced glass table resprite

### ISSUE THREAD

**Issue by Aineias1** [Goob-Station/Goob-Station#655]
It looks Ass
![image](https://github.com/user-attachments/assets/eaa622f2-c897-4d5d-9def-2e908cce49e2)

**Comment by BeeRobynn** [comment]
I remade the normal glass alongside the reinforced glass table, would this be good for a resprite or no
![image](https://github.com/user-attachments/assets/6d9b08a5-d31e-4a15-8b00-8f9de5432942)
![image](https://github.com/user-attachments/assets/9c5bb0c2-a5de-4928-8dba-301f84aa736f)

**Comment by Piras314** [comment]
depends on how it'd look ingame

**Comment by BeeRobynn** [comment]
![brighterlights](https://github.com/user-attachments/assets/e3668384-28cf-464d-8cb0-b5fd91ff859a)
![glass tables](https://github.com/user-attachments/assets/9a2a7f02-859f-46c2-b121-686a419bfa0a)
![mixed tables](https://github.com/user-attachments/assets/e6ef5ae0-e70e-4a47-8d26-683248019b4a)
![reinforcedglass tables](https://github.com/user-attachments/assets/30f18d3f-8661-45ea-98c1-a56a9189c26c)
here are all the staes in different situations

**Comment by Aineias1** [comment]
Honestly, make it more blue

**Comment by Aineias1** [comment]
https://github.com/Goob-Station/Goob-Station/pull/809
