### ISSUE TITLE
AI latejoin and multiAI broken

### ISSUE THREAD

**Issue by nymhole** [Goob-Station/Goob-Station#682]
## Description
only 1 ai can join on round start, and no one can latejoin as ai. 

**Screenshots**
![image_2024-09-23_014907040](https://github.com/user-attachments/assets/4977f6ba-db28-44d0-b679-28231b51ef3b)
(i also had station ai on high and was readied up for this round, i opened latejoin menu before observing)

**Additional context**
maybe merging with upstream will fix one of these? im not sure

**Comment by Piras314** [comment]
see if this can be reproduced after #680
