### ISSUE TITLE
Removing steel plate from intercom deletes encryption keys

### ISSUE THREAD

**Issue by GreyMario** [Goob-Station/Goob-Station#705]
## Description
Removing the steel plate protecting the maintenance panel on an intercom (ex. Security intercom) deletes the keys inside entirely (presumably due to an error caused by prototypes changing.)

**Reproduction**
1. Attempt to tide the encryption keys out of a Security intercom like a shitter.
2. Realize that you're now empty-handed.
3. Notice that the IntercomSecurity is now an IntercomConstructed.

**Comment by Aineias1** [comment]
@Piras314 done
