### ISSUE TITLE
Midround Nukies Die to Their Own Turrets

### ISSUE THREAD

**Issue by quri1q** [Goob-Station/Goob-Station#730]
## Description
Midround Nukies Die to Their Own Turrets, self explanitory, the turrets will target midround nuclear operatives that spawn due to dynamic gamemode, NOT the lone op

**Reproduction**
Spawn as a midround nukie named urist(its own issue) and go to the shuttle the turrets will shoot you

**Screenshots**
Forgot to take Screenshots

**Comment by whateverusername0** [comment]
lol what

**Comment by Teapug** [comment]
Thats a feature, nanotrasen just hacked the turrets
![image](https://github.com/user-attachments/assets/c73a458e-8bf0-4ac4-afdb-872554bdff21)

**Comment by whateverusername0** [comment]
@quri1q wait, there's midround nukies? NOT the lone op? what does that even mean

**Comment by quri1q** [comment]
> @quri1q wait, there's midround nukies? NOT the lone op? what does that even mean

In the dynamic game mode, nukies can spawn midround, and they are actual nukies, it seems to spawn in the entire nukie planet and shuttle too
