### ISSUE TITLE
the merc web vest is incorrectly contraband marked

### ISSUE THREAD

**Issue by JoeHammad1844** [Goob-Station/Goob-Station#733]
## Description

it's marked as syndicate contraband, which is incorrect as it is not affiliated with the syndicate

it should be marked as major contraband as it is still contraband but is not affiliated with the syndicate

this should be upstreamed by the way

**Comment by BeeRobynn** [comment]
![image](https://github.com/user-attachments/assets/dfdd7664-ea7e-49ef-ad7b-e50a066c8fc6)
fixed, was using the web vest as a parent so it was automatically adopting syndicate contraband level

**Comment by JoeHammad1844** [comment]
When the test build is outdated :finnadie:
