### ISSUE TITLE
Camera bugs from Syndie Surplus Crates allow AI Vision, letting them catch syndies instantly

### ISSUE THREAD

**Issue by BeeRobynn** [Goob-Station/Goob-Station#750]
## Description
When you get a surplus crate with a camera bug in it, the AI can see through it and see what you're doing with it, making it a guaranteed exposure if they're looking. This probably shouldn't be a thing

**Reproduction**
- get Surplus crate
- has camera bug
- ai pops in to look
- you are now valid

**Comment by AstroDogeDX** [comment]
I think this can be closed; tried to repro and the camera bug definitely doesn't have the ai vision component on it anymore.

**Comment by Piras314** [comment]
Same for me.
