### ISSUE TITLE
Mail teleporter not working

### ISSUE THREAD

**Issue by SirCannonFodder** [Goob-Station/Goob-Station#758]
## Description
I've waited 60+ minutes after turning the teleporter on and the station gotten not a single package.
This has happened to me on a shift in Fland and one in Oasis.
**Reproduction**
Turn on Mail teleporter, go AFK and cook dinner, come back to a mailess mail room. :(

**Screenshots**
![GitHub1](https://github.com/user-attachments/assets/6b4d4386-5722-426b-9b66-6c8c19ff288f)
![GitHub2](https://github.com/user-attachments/assets/7192fdd4-e997-4c01-ba1a-6179dc714548)

**Additional context**
I recall the mail system working fine on Oct 9th so it may be a stemming from one of the merged requests done on Oct 10th.

**Comment by AstroDogeDX** [comment]
This got fixed recently, this issue can be closed I reckon!
