### ISSUE TITLE
ling bug that puts you in stasis when selecting certain mutations

### ISSUE THREAD

**Issue by JoeHammad1844** [Goob-Station/Goob-Station#768]
## Description

i was trying to select a sting but i went into stasis

**Screenshots**
>

https://github.com/user-attachments/assets/8ea48e2a-835d-4040-a383-979f8d1e20ff

**Comment by JoeHammad1844** [comment]
i think it's tied to the arm blade because someone else said they went into stasis when they selected arm blade and i kinda fat fingered the sting

**Comment by JoeHammad1844** [comment]
also this fucked up my round i want an antag token :trollface:

**Comment by BombasterDS** [comment]
Not ling bug, wizden actions bar bug. You was on second action bar page when your it displayed actions from first page. It's often happens after transformation.

**Comment by JoeHammad1844** [comment]
well shit
