### ISSUE TITLE
Can't eject Borg brains or modules

### ISSUE THREAD

**Issue by SkippyMcSkips** [Goob-Station/Goob-Station#800]
## Description
When you try to eject a brain or module from a Borg, nothing happens. There's no error message, either. I've had to resort to destroying the Borg's body to get their brain or modules out to transfer to another new Borg body.

**Reproduction**
Unlock and open a Borg
Try to eject anything from them

**Additional context**
Upstream report: https://github.com/space-wizards/space-station-14/issues/32987

**Comment by BombasterDS** [comment]
> ## Description
> When you try to eject a brain or module from a Borg, nothing happens. There's no error message, either. I've had to resort to destroying the Borg's body to get their brain or modules out to transfer to another new Borg body.
> 
> **Reproduction** Unlock and open a Borg Try to eject anything from them
> 
> **Additional context** Upstream report: [space-wizards/space-station-14#32987](https://github.com/space-wizards/space-station-14/issues/32987)

This is goob problem, not wizden problem

**Comment by deltanedas** [comment]
you can use verb to eject battery thats it
probably related to being a decade behind upstream :trollface:

**Comment by BombasterDS** [comment]
> you can use verb to eject battery thats it probably related to being a decade behind upstream :trollface:

It's happening because of goob preferred name
