### ISSUE TITLE
vulp hands are switched

### ISSUE THREAD

**Issue by deltanedas** [Goob-Station/Goob-Station#822]
## Description
left is right, right is left

![03:56:09](https://github.com/user-attachments/assets/f6219aed-212d-4c75-826f-02083e9839a2)

may be an event issue

**Comment by Piras314** [comment]
was able to reproduce this, no idea why it's happening though

**Comment by Piras314** [comment]
HAHAHA I FIXED IT OH MY GOD THAT'S SO FUNNY AND DUMB

**Comment by Piras314** [comment]
applies to felinids and harpies, fixing it for them as well

**Comment by Piras314** [comment]
Fixed by #824

**Comment by AstroDogeDX** [comment]
oh lmao I was about to make a PR to fix this; the reason why it's broken is SO DUMB.

**Comment by deltanedas** [comment]
> Fixed by #824

pro you write `fixed #824` in the pr for it to autoclose

**Comment by Piras314** [comment]
Fixed #824
