### ISSUE TITLE
some species organs dont register

### ISSUE THREAD

**Issue by ARMOKS** [Goob-Station/Goob-Station#874]
## Description
In surgery some species organs dont register for removal, one example is slime, which cannot have organs removed, including brain
**Reproduction**
surgery on slime, try to remove brain / organs

**Comment by gluesniffler** [comment]
Fixed in #882. Thanks @deltanedas

**Comment by gluesniffler** [comment]
As for Slime cores and such, they can be hardcoded, but this will be a growing pain, might need to refactor surgery to start referencing prototypes so I can know when a bullshit unique organ is present or not, and if it needs to be displayed.
