### ISSUE TITLE
Cure wheelchair-bound by just standing up

### ISSUE THREAD

**Issue by BurningButter** [Goob-Station/Goob-Station#991]
## Description
When you are unable to move on your own without the assistance of a wheelchair you are able to simply, stand back up. I tested this as a wheelchair bound character but have not tested it as a character with legs/feet removed during surgery.

**Reproduction**
- Spawn as a wheelchair bound character
- Fall out of your wheelchair
- Stand back up (press r)

**Comment by deltanedas** [comment]
this doesnt work on someone who has their legs removed surgically

**Comment by BurningButter** [comment]
Interestingly I have been unable to reproduce this for a second time, not sure what I did differently the first time. What may have happened the first time was that I somehow cured it in a different way which caused me to assume that you could just stand up once I fell out. In either case there is still some sort of issue that allows wheelchair bound characters to cure their condition during normal gameplay.

**Comment by Aviu00** [comment]
Fixed by #1239
